### ISSUE TITLE
npx usage broken in version 2.0.0 

### ISSUE THREAD

**Issue by larsmars** [CycloneDX/cyclonedx-node-module#74] opened 2020-08-03 08:27 UTC
Running command:

`npx @cyclonedx/bom@1.1.3 -o bom.xml`

Bom is generated perfekt.

Running command:
`npx @cyclonedx/bom -o bom.xml` OR ` npx @cyclonedx/bom -o super-bom.xml -a composer-bom.xml`

Bom is **NOT** generated.

Error:
\AppData\Roaming\npm-cache\_npx\5908\node_modules\@cyclonedx\bom\node_modules\packageurl-js\src\package-url.js:28
        throw new Error('Invalid purl: "' + key + '" is a required field.');

Error: Invalid purl: "name" is a required field.

Nothing in release notes about updating commands for generation of bom files.

**Comment by coderpatros** [comment] 2020-08-03 08:45
Hi @larsmars npx usage is still working for me. Are you able to share any details about the project and environment where it is failing?

**Comment by larsmars** [comment] 2020-08-03 08:55
Yes,
npx -v 6.13.4 (dev machin)
node -v v12.16.1 (dev machin)

Drop from jenkins env. (img) 
![image (9)](https://user-images.githubusercontent.com/5154589/89164710-b6a03a80-d577-11ea-82f4-624b69cb161b.png)

**Comment by coderpatros** [comment] 2020-08-03 09:02
Can you share composer-bom.xml and your packages json?

**Comment by larsmars** [comment] 2020-08-03 09:10
package.json:
![image](https://user-images.githubusercontent.com/5154589/89165788-590ced80-d579-11ea-8796-af030d65ceb8.png)

 composer-bom.xml not needed because `npx @cyclonedx/bom -o bom.xml `gives the same error?
![image](https://user-images.githubusercontent.com/5154589/89166201-f2d49a80-d579-11ea-966f-c4f93b971213.png)

**Comment by larsmars** [comment] 2020-08-03 09:14
All good at version 1.1.3
![image](https://user-images.githubusercontent.com/5154589/89166551-81491c00-d57a-11ea-9042-c51773c18a64.png)

**Comment by coderpatros** [comment] 2020-08-03 09:46
Any chance you can copy/paste the package.json file instead of a screenshot. Just trying to reproduce it locally.

**Comment by larsmars** [comment] 2020-08-03 10:11
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "create-bom": "npx @cyclonedx/bom@1.1.3 -o super-bom.xml -a composer-bom.xml"
    },
    "devDependencies": {
        "@fortawesome/fontawesome-free": "^5.9.0",
        "axios": "^0.19.2",
        "bootstrap": "^4.1.0",
        "cross-env": "^5.1.6",
        "jquery": "^3.5.1",
        "laravel-mix": "^4.0.7",
        "lodash": "^4.17.19",
        "popper.js": "^1.12",
        "resolve-url-loader": "^2.3.1",
        "sass": "^1.26.3",
        "sass-loader": "^7.1.0",
        "vue": "^2.5.17",
        "vue-template-compiler": "^2.6.10"
    },
    "dependencies": {
        "file-saver": "^2.0.2",
        "json2csv": "^5.0.1",
        "vue-router": "^3.1.3",
        "vuex": "^3.1.1"
    }
}

**Comment by coderpatros** [comment] 2020-08-03 11:42
Looks like the latest version is expecting a name in the package.json like this...
```
{
    "name": "test",
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "create-bom": "npx @cyclonedx/bom -o super-bom.xml -a composer-bom.xml"
    },
    "devDependencies": {
        "@fortawesome/fontawesome-free": "^5.9.0",
        "axios": "^0.19.2",
        "bootstrap": "^4.1.0",
        "cross-env": "^5.1.6",
        "jquery": "^3.5.1",
        "laravel-mix": "^4.0.7",
        "lodash": "^4.17.19",
        "popper.js": "^1.12",
        "resolve-url-loader": "^2.3.1",
        "sass": "^1.26.3",
        "sass-loader": "^7.1.0",
        "vue": "^2.5.17",
        "vue-template-compiler": "^2.6.10"
    },
    "dependencies": {
        "file-saver": "^2.0.2",
        "json2csv": "^5.0.1",
        "vue-router": "^3.1.3",
        "vuex": "^3.1.1"
    }
}
```

**Comment by larsmars** [comment] 2020-08-03 12:00
Then it works here to 👍

**Comment by coderpatros** [comment] 2020-08-03 12:25
Thanks for confirming that @larsmars, a fix is pending

**Comment by stevespringett** [comment] 2020-08-03 14:55
Name is a required part of the PURL spec. So if it's not specified in the package.json, then we'll have to omit creating the PURL for it.

**Comment by coderpatros** [comment] 2020-09-04 23:07
Fixed in latest release

**Closed** 2020-09-04 23:06 UTC
