### ISSUE TITLE
-o and --output no longer work

### ISSUE THREAD

**Issue by ddurham2** [CycloneDX/cyclonedx-node-module#141] opened 2021-07-02 17:13 UTC
Recently, the -o and --output flags seem to have no effect.  It always outputs to bom.xml now

**Comment by stevespringett** [comment] 2021-07-02 17:58
Duplicate of #138

**Comment by coderpatros** [comment] 2021-07-02 22:25
Hi @ddurham2, this has been resolved in v3.0.2

**Closed by coderpatros** 2021-07-02 22:25 UTC
Labels: duplicate
