### ISSUE TITLE
No dependencies in the generated bom

### ISSUE THREAD

**Issue by hevelaska** [CycloneDX/cyclonedx-node-module#269] opened 2022-03-03 10:09 UTC
Hi,
I can't seem to have my dependencies listed in the bom.json file generated by cyclonedx. 

Project used:
https://github.com/Ismaestro/angular-example-app
node version : v16.14.0
cycloneDx version : 3.4.1

I tried to run `npm install` before running cyclonedx, and the node_modules folder is full. 

The command used: `cyclonedx-node -o bom.json`

The resulting file, missing `dependencies`:
```json
{
  "bomFormat": "CycloneDX",
  "specVersion": "1.3",
  "serialNumber": "urn:uuid:99d504c0-cd30-47e3-88bb-bc57caefc4cf",
  "version": 1,
  "metadata": {
    "timestamp": "2022-03-03T09:58:53.499Z",
    "tools": [
      {
        "vendor": "CycloneDX",
        "name": "Node.js module",
        "version": "3.4.1"
      }
    ],
    "component": {
      "type": "library",
      "bom-ref": "pkg:npm/angular-example-app@13.1.0",
      "name": "angular-example-app",
      "version": "13.1.0",
      "description": "<p align=\"center\">\r   <h3 align=\"center\">Angular Example App</h3>",
      "licenses": [
        {
          "license": {
            "id": "MIT"
          }
        }
      ],
      "purl": "pkg:npm/angular-example-app@13.1.0"
    }
  },
  "components":[...]
}
```

Things I tried:
- Removing the package.json file (bad idea, doesn't work)
- Removing the package-lock.json
- Removing all devDependencies in the package.json
- Using the --include-dev parameter

None of it seems to work.

**Comment by jkowalleck** [comment] 2022-03-03 17:17
I love your report, @hevelaska . all the needed details in it, a reproducible environment is given, no information left out.  :heart_decoration: 

Unfortunately, there is nothing wrong with your results. not a bug :-) 
Just the "wrong" expectations: the nodejs implementation is lacking the feature of dependency graph.

The original feature request is #61
Therefore, i will close this report as a duplicate.

**Closed by jkowalleck** 2022-03-03 17:17 UTC
